# Generated by Django 3.1.4 on 2021-01-12 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicio',
            old_name='crated',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='servicio',
            old_name='update',
            new_name='updated',
        ),
        migrations.AlterField(
            model_name='servicio',
            name='imagen',
            field=models.ImageField(upload_to='servicios'),
        ),
    ]
